#############################################################################
# Makefile for building: LiteralDraw
# Generated by qmake (2.01a) (Qt 4.7.0) on: Thu Apr 14 10:01:07 2011
# Project:  LiteralDraw.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile LiteralDraw.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_SVG_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtSvg -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtSvg -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		literal.cpp \
		draw.cpp \
		svgview.cpp \
		command.cpp \
		drawview.cpp \
		literalmodel.cpp moc_mainwindow.cpp \
		moc_literal.cpp \
		moc_draw.cpp \
		moc_svgview.cpp \
		moc_command.cpp \
		moc_drawview.cpp \
		moc_literalmodel.cpp
OBJECTS       = main.o \
		mainwindow.o \
		literal.o \
		draw.o \
		svgview.o \
		command.o \
		drawview.o \
		literalmodel.o \
		moc_mainwindow.o \
		moc_literal.o \
		moc_draw.o \
		moc_svgview.o \
		moc_command.o \
		moc_drawview.o \
		moc_literalmodel.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		LiteralDraw.pro
QMAKE_TARGET  = LiteralDraw
DESTDIR       = 
TARGET        = LiteralDraw

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_literal.h ui_draw.h ui_svgview.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: LiteralDraw.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/debug.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtSvg.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile LiteralDraw.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/debug.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtSvg.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile LiteralDraw.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/LiteralDraw1.0.0 || $(MKDIR) .tmp/LiteralDraw1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/LiteralDraw1.0.0/ && $(COPY_FILE) --parents mainwindow.h literal.h draw.h svgview.h command.h drawview.h literalmodel.h .tmp/LiteralDraw1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp literal.cpp draw.cpp svgview.cpp command.cpp drawview.cpp literalmodel.cpp .tmp/LiteralDraw1.0.0/ && $(COPY_FILE) --parents mainwindow.ui literal.ui draw.ui svgview.ui .tmp/LiteralDraw1.0.0/ && (cd `dirname .tmp/LiteralDraw1.0.0` && $(TAR) LiteralDraw1.0.0.tar LiteralDraw1.0.0 && $(COMPRESS) LiteralDraw1.0.0.tar) && $(MOVE) `dirname .tmp/LiteralDraw1.0.0`/LiteralDraw1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/LiteralDraw1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_literal.cpp moc_draw.cpp moc_svgview.cpp moc_command.cpp moc_drawview.cpp moc_literalmodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_literal.cpp moc_draw.cpp moc_svgview.cpp moc_command.cpp moc_drawview.cpp moc_literalmodel.cpp
moc_mainwindow.cpp: command.h \
		mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_literal.cpp: literal.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) literal.h -o moc_literal.cpp

moc_draw.cpp: draw.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) draw.h -o moc_draw.cpp

moc_svgview.cpp: svgview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) svgview.h -o moc_svgview.cpp

moc_command.cpp: command.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) command.h -o moc_command.cpp

moc_drawview.cpp: drawview.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) drawview.h -o moc_drawview.cpp

moc_literalmodel.cpp: literalmodel.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) literalmodel.h -o moc_literalmodel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_literal.h ui_draw.h ui_svgview.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_literal.h ui_draw.h ui_svgview.h
ui_mainwindow.h: mainwindow.ui \
		literal.h \
		draw.h \
		svgview.h
	/usr/bin/uic-qt4 mainwindow.ui -o ui_mainwindow.h

ui_literal.h: literal.ui
	/usr/bin/uic-qt4 literal.ui -o ui_literal.h

ui_draw.h: draw.ui \
		drawview.h
	/usr/bin/uic-qt4 draw.ui -o ui_draw.h

ui_svgview.h: svgview.ui
	/usr/bin/uic-qt4 svgview.ui -o ui_svgview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		command.h \
		ui_mainwindow.h \
		literalmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

literal.o: literal.cpp literal.h \
		ui_literal.h \
		command.h \
		literalmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o literal.o literal.cpp

draw.o: draw.cpp draw.h \
		ui_draw.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o draw.o draw.cpp

svgview.o: svgview.cpp svgview.h \
		ui_svgview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o svgview.o svgview.cpp

command.o: command.cpp command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o command.o command.cpp

drawview.o: drawview.cpp drawview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drawview.o drawview.cpp

literalmodel.o: literalmodel.cpp literalmodel.h \
		command.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o literalmodel.o literalmodel.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_literal.o: moc_literal.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_literal.o moc_literal.cpp

moc_draw.o: moc_draw.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_draw.o moc_draw.cpp

moc_svgview.o: moc_svgview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_svgview.o moc_svgview.cpp

moc_command.o: moc_command.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_command.o moc_command.cpp

moc_drawview.o: moc_drawview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_drawview.o moc_drawview.cpp

moc_literalmodel.o: moc_literalmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_literalmodel.o moc_literalmodel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

